wsgi/pico/pico/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'pico.views.page_not_found'
#handler500 = 'pico.views.server_error'

admin.autodiscover()

#urlpatterns = patterns('',
#    url(r'^i18n/', include('django.conf.urls.i18n')),
#)

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}, name='sitemap-xml'),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^pico_blog/', include('pico_blog.urls', namespace='pico_blog')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

wsgi/pico/pico_blog/urls.py
from django.conf.urls import patterns, url
from pico_blog.views import PostListView, PostDetailView, CategoryListView, PostArchiveListView, TagListView, AuthorPostListView, search

urlpatterns = patterns (
	'',
	url(r'^$', PostListView.as_view(), name='post-list'),
	url(r'(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$', PostDetailView.as_view(), name='post-detail'),
	url(r'^category/(?P<category>[\w\.@+-]+)/$', CategoryListView.as_view(), name='category-post-list'),
	url(r'^(?P<year>\d{4})/$', PostArchiveListView.as_view(), name='archive-post-list'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostArchiveListView.as_view(), name='archive-post-list'),
	url(r'^tag/(?P<tag>[-\w]+)/$', TagListView.as_view(), name='tag-post-list'),
	url(r'^author/(?P<username>[\w\.@+-]+)/$', AuthorPostListView.as_view(), name='author-post-list'),
	url(r'^search/$', search, name='search'),
)

wsgi/pico/pico/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def page_not_found(request):
	response = render_to_response('404.html', context_instance=RequestContext(request))
	response.status_code = 404
	return response

def server_error(request):
	response = render_to_response('500.html', context_instance=RequestContext(request))
	response.status_code = 500
	return response

wsgi/pico/pico/templates/base.html
{% load cms_tags staticfiles sekizai_tags menu_tags pico_blog_tags %}
<!doctype html>
<html class="no-js" lang="jv">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        {% block meta_header %}
        <title>ꦄꦏ꧀ꦱꦫ</title>
        <meta name="description" content="Halaman bertuliskan aksara jawa">
        {% endblock meta_header %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->
        <link rel="stylesheet" href="{% static 'pico/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'pico/css/pico.css' %}">
        <link rel="stylesheet" href="{% static 'pico/css/font-awesome.min.css' %}">
        <script src="{% static 'pico/js/modernizr-2.8.3.js' %}"></script>
        {% render_block "css" %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        {% cms_toolbar %}

        <div class="site-wrapper">
            {% block header %}
            <div class="site-cover">
                <div class="cover-inner">
                    <div class="site-feature">
                        <h1 class="site-title">ꦄꦏ꧀ꦱꦫ</h1>
                        <h2 class="description">ꦠꦸꦭꦶꦱꦤ꧀ꦥꦫꦎꦫꦁꦗꦮꦩꦱꦏꦶꦤꦶ</h2>
                    </div>
                </div>
            </div>
            {% endblock header %}
            {% block navigation %}
            <div class="site-navigation">
                <nav class="navbar navbar-default">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="{{ SITE_DOMAIN }}">ꦄꦏ꧀ꦱꦫ</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <form action="{% url 'pico_blog:search' %}" class="navbar-form navbar-right" role="search" method="get">
                                <div class="form-group">
                                    <!-- <input type="text" class="form-control" placeholder="Search"> -->
                                    {% search_form %}
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                            <ul class="nav navbar-nav navbar-right">
                                {% show_menu 0 1 100 100 "menu.html" %}
                            </ul>

                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav><!-- END OF NAVIGATION BAR -->
            </div>
            {% endblock navigation %}

            <div class="site-main">
                <div class="site-main-inner">
                    {% block content %}{% endblock content %}
                </div>
            </div>
            <div class="site-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">{% static_placeholder "footer" %}</div>
                    </div>
                </div>
            </div>
        </div>


        <script type="text/javascript" src="{% static 'pico/js/jquery-1.11.3.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pico/js/bootstrap.min.js' %}"></script>
        {% render_block "js" %}

        <script type="text/javascript">
            var navbar = $(".navbar");
            var siteCover = $(".site-cover");
            $(window).scroll(function() {
                /* Act on the event */
                if($(this).scrollTop() > siteCover.height()) {
                    navbar.addClass("navbar-fixed-top");
                } else {
                    navbar.removeClass("navbar-fixed-top");
                }
            });
        </script>
    </body>
</html>

wsgi/pico/pico/templates/comming_soon.html
{% load cms_tags staticfiles sekizai_tags menu_tags %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{% block title %}{% page_attribute "page_title" %}{% endblock title %}</title>
		<link rel="stylesheet" href="{% static 'pico/css/comming_soon.css' %}">
		<link rel="stylesheet" href="{% static 'pico/css/countdown.css' %}">
		{% render_block "css" %}
	</head>
	<body>
		{% cms_toolbar %}
		<div class="cover-wrapper">
			<div class="cover-container">
				<div class="cover-inner">
					<img class="top" src="{% static 'pico/img/top-border.svg' %}" alt="">
					<h1 class="greetings">ꦱꦼꦏꦼꦢꦥ꧀ꦩꦭꦶꦃ</h1>
					<p>ꦲꦭꦩꦤ꧀ꦥꦸꦤꦶꦏꦶꦠꦏ꧀ꦱꦶꦃꦲꦶꦁꦥꦿꦺꦴꦱꦼꦱ꧀</p>
					<div id="clockdiv">
						<div class="time-container">
					    	<span class="days"></span>
					    	<span class="smalltext"> ꦢꦶꦤ</span>
					  	</div>
					  	<div class="time-container">
					    	<span class="hours"></span>
					    	<span class="smalltext"> ꦗꦩ꧀</span>
					  	</div>
					  	<div class="time-container">
					    	<span class="minutes"></span>
					    	<span class="smalltext"> ꦩꦼꦤꦶꦠ꧀</span>
					  	</div>
					  	<div class="time-container">
					   		<span class="seconds"></span>
					    	<span class="smalltext"> ꦢꦺꦠꦶꦏ꧀</span>
					  	</div>
					</div>
					<img class="bottom" src="{% static 'pico/img/bottom-border.svg' %}" alt="">
				</div>
			</div>
		</div>

        {% render_block "js" %}
        <!-- jQuery and Modernizr-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
		<script src="{% static 'pico/js/countdown.js' %}"></script>
	</body>
</html>

wsgi/pico/pico/templates/feature.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="jumbotron">
        {% placeholder "feature" %}
    </div>
    <div>
        {% placeholder "content" %}
    </div>
{% endblock content %}

wsgi/pico/pico/templates/menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
    <li class="{% if child.ancestor %}ancestor{% endif %}
        {% if child.selected %} active{% endif %}
        {% if child.children %} dropdown{% endif %}">
        {% if child.children %}
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ child.get_menu_title }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
            </ul>
        {% else %}
            <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
        {% endif %}
    </li>
    {% if class and forloop.last and not forloop.parentloop %}{% endif %}
{% endfor %}

wsgi/pico/pico/templates/page.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}